/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.21
 * Generated at: 2016-07-26 15:54:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import security.demo.ligne.*;

public final class test_jsp extends security.web.servlet.Jsp
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

   Ligne ligne=Ligne.get();
   if (ligne != null) {

      out.write("\n");
      out.write("\n");
      out.write("Code: ");
      out.print(html(ligne.code) );
      out.write("</p>\n");
      out.write("name: ");
      out.print(html(ligne.name) );
      out.write("</p>\n");
      out.write("description: ");
      out.print(html(ligne.description) );
      out.write("</p>\n");
      out.write("date: ");
      out.print(date(ligne.date) );
      out.write("</p>\n");
      out.write("number: ");
      out.print(html(ligne.number) );
      out.write("</p>\n");
      out.write("percent: ");
      out.print(html(ligne.percent) );
      out.write("%</p>\n");
 } else { 
      out.write("\n");
      out.write("Empty ligne\n");
 } 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<form action=\"/web-security-demo/s/ModifyLigne\">\n");
      out.write("\n");
      out.write("name:<textarea name=\"name\"></textarea></p>\n");
      out.write("code:<textarea name=\"code\"></textarea></p>\n");
      out.write("description:<textarea name=\"description\"></textarea></p>\n");
      out.write("date:<textarea name=\"date\"></textarea></p>\n");
      out.write("number:<textarea name=\"number\"></textarea></p>\n");
      out.write("double:<textarea name=\"percent\"></textarea></p>\n");
      out.write("\n");
      out.write("<input type=\"submit\" name=\"OK\" value=\"Sumit\">\n");
      out.write("</form>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
